---
# tasks file for astra-ebs

  - name: Enabled SSH Service
    service:
      name: ssh
      enabled: yes

  - name: Creates directory /home/{{ ansible_env.SUDO_USER }}/iso for copy update image
    file:
      path:  /home/{{ ansible_env.SUDO_USER }}/iso
      state: directory

  - name: Creates directory /home/{{ ansible_env.SUDO_USER }}/iso_m for mount repo
    file:
      path:  /home/{{ ansible_env.SUDO_USER }}/iso_m
      state: directory


  - name: Copy Update {{ NAME_ISO_UPDATE_FILE }} to Astra
    copy:
      src:  "{{ NAME_ISO_UPDATE_FILE }}"
      dest: /home/{{ ansible_env.SUDO_USER }}/iso
      mode: 0777

  - name: mount repo
    mount:
      src:     /home/{{ ansible_env.SUDO_USER }}/iso/20211126SE16.iso
      path:    /home/{{ ansible_env.SUDO_USER }}/iso_m
      fstype:  iso9660
      opts:    ro
      state:   mounted

  - name: Add specified repository into sources list
    template:
      src: sources.list.j2 # deb file:///home/{{ ansible_env.SUDO_USER }}/iso_m smolensk contrib main non-free
      dest: /etc/apt/sources.list


  - name: Update repository chache
    apt:
      update_cache: yes

  - name: Upgrade the OS
    apt:
      upgrade: yes


  - name: install and update Core Linux linux-5.10
    apt:
      name:  linux-5.10
      state: latest

  - name: Remove older core linux-4.15
    apt:
      pkg:
      -      linux-4.15*
      -      linux-image-4.15*
      -      linux-headers-4.15*
      state: absent

  - name:     Update GRUB
    shell:    update-grub2
    register: results

  - name: --- GRUB DEBUG ---
    debug:
      var: results.stderr_lines


  - name: Checking the installed Cifs, ntp and Zip-Archiver
    apt:
     pkg:
     -      zip
     -      cifs-utils
     -      ntpdate
     -      ntp
     state: latest


  - name: umonte repo
    mount:
      path:  /home/{{ ansible_env.SUDO_USER }}/iso_m
      state: unmounted


  - name: Creates directory "/home/{{ ansible_env.SUDO_USER }}/TrustGate_versions"
    file:
      path:  /home/{{ ansible_env.SUDO_USER }}/TrustGate_versions
      state: directory

  - name: Copy TrustGate Archive
    copy:
      src:  "{{ TRUSTGATE_ZIP_FILE_NAME }}"
      dest: /home/{{ ansible_env.SUDO_USER }}/TrustGate_versions
      mode: 0777

  - name: Creates directory "distr"
    file:
      path:  /home/{{ ansible_env.SUDO_USER }}/distr
      state: directory

  - name: UnZip TrustGate archive
    unarchive:
      src:         /home/{{ ansible_env.SUDO_USER }}//TrustGate_versions/{{ TRUSTGATE_ZIP_FILE_NAME }}
      dest:        /home/{{ ansible_env.SUDO_USER }}/distr
      remote_src:  yes

  - name: Creates directory "/home/{{ ansible_env.SUDO_USER }}/drweb"
    file:
      path:  /home/{{ ansible_env.SUDO_USER }}/drweb
      state: directory

  - name: Copy drweb.run
    copy:
      src: "{{ DRWEB_RUN_FILE_NAME }}"
      dest: /home/{{ ansible_env.SUDO_USER }}/drweb
      mode: 0777

  - name: Copy scripts for DrWeb
    copy:
      src: "{{ item }}"
      dest: /home/{{ ansible_env.SUDO_USER }}/drweb
    with_items:
        - "bootscan-drweb.sh"
        - "dscan-drweb.sh"

  - name: Generate drweb-update.sh
    template:
      src:  drweb-update.sh.j2
      dest: /home/{{ ansible_env.SUDO_USER }}/drweb/drweb-update.sh
      mode: 0555

  - name: CRONTAB for drweb-update.sh
    cron:
      name: "DrWeb update bases"
      minute: "0"
      hour: "6"
      job: "/home/{{ ansible_env.SUDO_USER }}/drweb/drweb-update.sh"

  - name: CRONTAB for bootscan-drweb.sh
    cron:
      name: "DrWeb bootscan"
      minute: "0"
      hour: "23"
      job: "/home/{{ ansible_env.SUDO_USER }}/drweb/bootscan-drweb.sh"

  - name: CRONTAB for dscan-drweb.sh
    cron:
      name: "DrWeb dscan"
      minute: "0"
      hour: "22"
      job: "/home/{{ ansible_env.SUDO_USER }}/drweb/dscan-drweb.sh"

  - name:     Crontab tasks check
    shell:    crontab -l
    register: results

  - name: --- CRONTAB DEBUG ---
    debug:
      var: results.stdout_lines

  - name: Generate UserLogon file
    template:
      src:    UserLogon.j2
      dest:   /root/.UserLogon.txt
      mode:   0555

  - name: Generate ntp.conf
    template:
      src:    ntp.conf.j2
      dest:   /etc/ntp.conf
      mode:   0555

  - name: Enabled and restart NTP Service
    service:
      name:    ntp
      state:   restarted
      enabled: yes

  - name: Reboot server
    reboot:
      reboot_timeout: 3600

